### ISSUE TITLE
There is no complete output after the concolic execution.

### ISSUE THREAD

**Issue by abc767234318** [formalsec/wasp#1]
I made a few changes to 2o1u.wast for the btree dataset and executed the following command:
```
wasp -t 2o1u.wast
```
The program then stops after 900 seconds or so, with the following output:
```
-- Running ("(input \"2o1u.wast\")")...
-- Parsing...
-- Running...
-- Loading (2o1u.wast)...
-- Parsing...
-- Running...
-- Checking...
-- Initializing...
-- Invoking function "main"...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ITERATION NUMBER 001 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

>>> Assume passed. Continuing execution...
```
I wonder if there is a timeout set within the wasp program.

**Comment by filipeom** [comment]
Sorry for the delayed response @abc767234318. There is indeed a default timeout of 900s which can be modified with the flag `--timeout` as described in `wasp --help`. One may also disable this feature with the following argument `--timeout -1`.
